### ISSUE TITLE
_DecoratorContextManager.__call__() got an unexpected keyword argument 'input_ids'

### ISSUE THREAD

**Issue by ffflesleo** [QQ-MM/Video-CCAM#10]
Traceback (most recent call last):
  File "/home/liudi/model/Video-CCAM-main/test.py", line 45, in <module>
    response = videoccam.chat(messages, images, tokenizer, image_processor, max_new_tokens=512, do_sample=False)
  File "/home/hisense/.cache/huggingface/modules/transformers_modules/modeling_videoccam.py", line 367, in chat
    output_ids = self.generate(
TypeError: _DecoratorContextManager.__call__() got an unexpected keyword argument 'input_ids'

**Comment by Jaron123s** [comment]
Sorry, but I cannot reproduce this without knowing your settings.
